name: Flutter Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # - name: Build
    #   working-directory: ${{github.workspace}}
    #   run: flutter build apk

    - name: Test
      working-directory: ${{github.workspace}}/carbongecko
      run: flutter test
